workflows:
  android-build:
    name: Android Build
    environment:
      vars:
        # Codemagic already has SDK installed
        ANDROID_HOME: /usr/local/lib/android/sdk
    scripts:
      - name: Build Debug APK
        script: ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk