workflows:
  android-build:
    name: Android Build
    environment:
      vars:
        ANDROID_HOME: /usr/local/lib/android/sdk
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk